# mkdocs.yml

site_name: Proyecto Modelo de Ising

theme:
  name: "material"

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocstrings:

nav:
  - General: index.md
  - Desarrollo: explanation.md
  - Resultados: result.md
  - Referencias: reference.md

